services:
  tigerbeetle:
    image: ghcr.io/tigerbeetle/tigerbeetle:latest
    container_name: tigerbeetle
    ports:
      - "3001:3001"
    volumes:
      - ./data:/data
    security_opt:
      - seccomp=unconfined
    cap_add:
      - IPC_LOCK
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "if [ ! -f /data/0_0.tigerbeetle ]; then
        /tigerbeetle format --cluster=0 --replica=0 --replica-count=1 /data/0_0.tigerbeetle;
      fi &&
      /tigerbeetle start --addresses=0.0.0.0:3001 /data/0_0.tigerbeetle"