version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rls-experiment-postgres
    environment:
      POSTGRES_DB: multitenant_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d multitenant_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: